// Generated by CoffeeScript 1.7.1
(function() {
  var batch, lib, tests;

  lib = {
    huwsettings: require('../index'),
    vows: require('vows'),
    assert: require('assert')
  };

  tests = lib.vows.describe('Testing features atomically');

  batch = {
    'when using environment variables': {
      topic: function() {
        var buckets, settings, values;
        buckets = {
          '$': {
            VAR: 'foobar'
          }
        };
        settings = {};
        values = {
          setting: '$VAR'
        };
        lib.huwsettings.extend(settings, values, buckets);
        return settings;
      },
      'we expect to get the correct value back': function(error, result) {
        return lib.assert.equal(result.setting, 'foobar');
      }
    }
  };

  tests.addBatch(batch);

  tests["export"](module);

}).call(this);
